Ignore all .png paths
Since I get errors like:

NoMethodError undefined method `title' for #<Mechanize::Image:0x007fb2b5d6f000> [ PATH /apple-touch-icon-120x120.png ]